version: "3.9"
services:
  api:
    image: "freelancers-crm"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1401:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Sasung24
    volumes:
      - C:/volumes:/var/opt/mssql/data